### PR TITLE
Removed png files that shouldn't be checked into the repo

### PR DESCRIPTION
**Pull request by lintool**
See title.

### CODE REVIEW

**Comment by gauchm** [comment]
I think rather than cleaning up master we should just abandon the current master branch and make `python` or `graham` the new master (and clean up those). What currently is `master` is just the old scala code.

On a more general note, we should come up with a concept of how we deal with the two frontends for the Graham and PySpark backends. Do we keep them in one repo with two branches or should we spilt one off?

**Comment by lintool** [comment]
@gauchm which current branch should I merge to master? I think for this, as an exception, we should do a merge commit and not squash.

**Comment by gauchm** [comment]
I'd take `python`, as this contains front- and backend code. `graham` has just frontend code.
I agree on not squashing the commits for this.

**Comment by lintool** [comment]
Closing, per discussion above, see #3

**Pull request closed without merging**
